name: Build

on:
  push:
    branches: [ main, "dev" ]
  pull_request:
    branches: [ main, "dev" ]

jobs:
  build_non_docker:
    name: Build non docker version
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Set up Go
      uses: actions/setup-go@v5.4.0
      with:
        go-version-file: go.mod
        cache-dependency-path: go.sum

    - name: Update apt
      env:
        DEBIAN_FRONTEND: noninteractive
      run:
        sudo apt-get update -qq -o Acquire::Retries=3

    - name: Start build script
      run: cargo build --bins --release

    # - name: Run image converter test
    #   run: go test -v ./imageConverter

  build_docker:
    name: Build docker version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3.6.0
        with:
          image: tonistiigi/binfmt:qemu-v9.2.2
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: buildDocker
        uses: docker/build-push-action@v6.16.0
        with:
          context: .
          push: false
          platforms: linux/amd64, linux/arm64
          tags:  pcpl2/easy_image_cdn:latest,ghcr.io/pcpl2/easy_image_cdn:latest
          build-args: |
            App_Version=latest
