name: Build

on:
  push:
    branches: [ main, "dev" ]
  pull_request:
    branches: [ main, "dev" ]

jobs:
  build_non_docker:
    name: Build non docker version
    strategy:
      matrix:
        include:
        - os: ubuntu-24.04
        - os: ubuntu-24.04-arm

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Set up rust
      uses: actions-rust-lang/setup-rust-toolchain@v1.12.0
      with:
        toolchain: stable

    - name: Update apt
      env:
        DEBIAN_FRONTEND: noninteractive
      run:
        sudo apt-get update -qq -o Acquire::Retries=3

    - name: Start build script
      run: cargo build --bins --release

    # - name: Run image converter test
    #   run: go test -v ./imageConverter

  build_docker:
    name: Build docker version
    strategy:
      matrix:
        include:
        - os: ubuntu-24.04
          platforms: linux/amd64
        - os: ubuntu-24.04-arm
          platforms: linux/arm64

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: buildDocker
        uses: docker/build-push-action@v6.16.0
        with:
          context: .
          push: false
          platforms: ${{ matrix.platforms }}
          tags:  pcpl2/easy_image_cdn:latest,ghcr.io/pcpl2/easy_image_cdn:latest
          build-args: |
            App_Version=latest
