name: Build

on:
  push:
    branches: [ main, "dev" ]
  pull_request:
    branches: [ main, "dev" ]

jobs:
  build_non_docker:
    name: Build non docker version
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.1.0

    - name: Set up Go
      uses: actions/setup-go@v3.3.1
      with:
        go-version-file: go.mod
        cache: true
        cache-dependency-path: go.sum

    - name: Update apt
      env:
        DEBIAN_FRONTEND: noninteractive
      run:
        sudo apt-get update -qq -o Acquire::Retries=3

    - name: Prepare go modules
      run: go env -w GO111MODULE=auto CGO_ENABLED=1 GOOS=linux && go get -d -v

    - name: Start build script
      run: go build -v -X 'easy-image-cdn.pcpl2lab.ovh/app/build.Version=latest' -X 'easy-image-cdn.pcpl2lab.ovh/app/build.Time=$(date)' ./...

    - name: Run image converter test
      run: go test -v ./imageConverter

  build_docker:
    name: Build docker version
    runs-on: ubuntu-latest

    steps:
      -  name: Checkout repository 
         uses: actions/checkout@v3.1.0

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2.1.0
        with:
          image: tonistiigi/binfmt:qemu-v7.0.0-28
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: buildDocker
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: false
          platforms: linux/amd64, linux/arm64
          tags:  pcpl2/easy_image_cdn:latest,ghcr.io/pcpl2/easy_image_cdn:latest
          build-args: |
            App_Version=latest
