name: Publish new version

on:
    workflow_dispatch:
      inputs:
        version:
          description: 'Server version (format: Major.Minor.HotFix, example: 1.2.12)'
          required: true
jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.1.0

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v2.1.0
      with:
        image: tonistiigi/binfmt:qemu-v7.0.0-28
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1

    - name: Login to Github packages
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Login to Docker hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DH_USERNAME }}
        password: ${{ secrets.DH_TOKEN }}

    - name: buildDocker
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        push: true
        platforms: linux/amd64, linux/arm64
        tags: pcpl2/easy_image_cdn:latest,pcpl2/easy_image_cdn:${{ github.event.inputs.version }},ghcr.io/pcpl2/easy_image_cdn:latest,ghcr.io/pcpl2/easy_image_cdn:${{ github.event.inputs.version }}

    - name: Create release on github
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Release ${{ github.event.inputs.version }}
        tag_name: ${{ github.event.inputs.version }}
