# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build cdn server on commit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Update apt
      env:
          DEBIAN_FRONTEND: noninteractive
      run: 
        sudo apt-get update -qq -o Acquire::Retries=3

    - name: Install libvips
      env:
        DEBIAN_FRONTEND: noninteractive
      run:
        # we only need the library
        sudo apt-get install --fix-missing -qq -o Acquire::Retries=3
          libvips-dev 

    - name: Prepare go modules
      run: go env -w GO111MODULE=auto CGO_ENABLED=1 GOOS=linux GOARCH=amd64 && go get -d -v

    - name: Start build script
      run: go build -v ./...
