name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_non_docker:
    name: Build non docker version
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.0.2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Update apt
      env:
          DEBIAN_FRONTEND: noninteractive
      run: 
        sudo apt-get update -qq -o Acquire::Retries=3

    - name: Prepare go modules
      run: go env -w GO111MODULE=auto CGO_ENABLED=1 GOOS=linux && go get -d -v

    - name: Start build script
      run: go build -v ./...

    - name: Run image converter test
      run: go test -v ./imageConverter
  
  build_docker:
    name: Build docker version
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: buildDocker
        uses: docker/build-push-action@v3.1.0
        with:
          context: .
          push: false
          platforms: linux/amd64, linux/arm64
          tags:  pcpl2/easy_image_cdn:latest,ghcr.io/pcpl2/easy_image_cdn:latest
