name: Deploy Nightly

on:
  schedule:
    - cron: '0 1 * * *' # run at 1 AM UTC

jobs:
  build:
    name: Build and publish
    strategy:
      matrix:
        include:
        - os: ubuntu-24.04
          platforms: linux/amd64
        - os: ubuntu-24.04-arm
          platforms: linux/arm64

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Login to Github packages
      uses: docker/login-action@v3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Login to Docker hub
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DH_USERNAME }}
        password: ${{ secrets.DH_TOKEN }}

    - name: buildDocker
      uses: docker/build-push-action@v6.15.0
      with:
        context: .
        push: true
        platforms: ${{ matrix.platforms }}
        tags: pcpl2/easy_image_cdn:nightly,ghcr.io/pcpl2/easy_image_cdn:nightly
        build-args: |
            App_Version=nightly
